[options]

# UX / Behavior
BottomUp
CombinedUpgrade
UpgradeMenu
NewsOnUpgrade
Provides
PgpFetch

# Build & Safety
SudoLoop
CleanAfter
RemoveMake = ask
SaveChanges

# Performance / Convenience
BatchInstall
CompletionInterval = 7

# Pacman interop
UseAsk

[bin]

# Use modern tools if available
Bat = bat
Pager = less -R


[env]

# Parallel builds (adjust to CPU threads)
MAKEFLAGS = -j 4
NINJAFLAGS= -j 4
