-- HYPRLAND CONFIG

-- Environment Vars
require("env")

-- Core behavior
require("input")
require("looks")
require("rules")

-- Keybindings
require("keybinds")

-- Other configs
require("conf")

-- Display
require("workspaces") -- defaults
require("monitors") -- autogenerated

-- Autostart
require("autostart")
