-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0x369F",
  mode = "1920x1080@60.04",
  position = "2560x0",
  scale = 1,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG IPS QHD 406NTAB1G616",
  mode = "2560x1440@74.96",
  position = "0x0",
  scale = 1,
  vrr = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Electronics LG IPS QHD 406NTAB1G616", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Electronics LG IPS QHD 406NTAB1G616", default = true, persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Electronics LG IPS QHD 406NTAB1G616", default = true, persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:LG Electronics LG IPS QHD 406NTAB1G616", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:LG Electronics LG IPS QHD 406NTAB1G616", default = true, persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:LG Electronics LG IPS QHD 406NTAB1G616", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:AU Optronics 0x369F", default = true, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:AU Optronics 0x369F", default = true, persistent = true })
hl.workspace_rule({ workspace = "9", monitor = "desc:AU Optronics 0x369F", default = true, persistent = true })
hl.workspace_rule({ workspace = "10", monitor = "desc:AU Optronics 0x369F", default = true, persistent = true })
