# Allow Thumbfast to work on network streams (yt-dlp)
network=yes

# Use hardware decoding for the background thumbnail generation (saves CPU)
hwdec=yes

# Maximum thumbnail size (pixels)
max_height=200
max_width=200

# How many seconds of video to process at once for thumbnails
# (Lowering this slightly helps responsiveness on 4K network streams)
spawn_first=yes
