# file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf

# If set this override the default TS_SEARCH_PATHS (~/ ~/personal ~/personal/dev/env/.config)
TS_SEARCH_PATHS=(~/ ~/.config ~/dev/** ~/docs/obsidian ~/data/** ~/lab)

# If set this add additional search paths to the default TS_SEARCH_PATHS
# The number prefix is the depth for the Path [OPTIONAL]
TS_EXTRA_SEARCH_PATHS=(/home)

# if set this override the TS_MAX_DEPTH (1)
# TS_MAX_DEPTH=2
